### ISSUE TITLE
Request for running on replit server 

### ISSUE THREAD

**Issue by steam34** [mfrashad/text2art#10]
Please make a article on how can I host this project on replit server because it is free for students in github student pack.

**Comment by mfrashad** [comment]
I don't think replit support GPU server. You can host the frontend on replit, but you still need a backend with GPU to do the image generation. Although, running it on CPU is still possible, it would be incredibly slow. (might take hours just to generate one image). 

The project is using Colab and Firebase for the backend by default, and both have free versions.

**Comment by shreesha345** [comment]
Can I run it full time in Colab the backend because Colab as some limitations and I can't pay for Colab 🙁
