### ISSUE TITLE
I am getting the same error 😢😭

### ISSUE THREAD

**Issue by shreesha345** [mfrashad/text2art#11]
![error](https://user-images.githubusercontent.com/71629361/147729931-a5ef418c-fb75-4971-86a2-8c228da4b38c.png)

please help here is the error 👇:

`AttributeError                           
 Traceback (most recent call last)
/tmp/ipykernel_32/3491049020.py in <module>
      1 import clipit
      2 # To reset settings to default
----> 3 clipit.reset_settings()
      4 # You can use "|" to separate multiple prompts
      5 prompts = "underwater city"

AttributeError: module 'clipit' has no attribute 'reset_settings'

`

**Comment by mfrashad** [comment]
It's probably due to an error in importing the clipit. Usually restarting the runtime, and running the setup again fixed the issue.
