### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CEM1204** [mfrashad/text2art#3]
AttributeError Traceback (most recent call last)
in ()
1 import clipit
2 # To reset settings to default
----> 3 clipit.reset_settings()
4 # You can use "|" to separate multiple prompts
5 prompts = "death sky rain"

AttributeError: module 'clipit' has no attribute 'reset_settings'

Always get this error when using the Colab. I run setup, restart runtime and then execute the next block. It breaks then.

**Comment by sandeeppatil1998** [comment]
AttributeError                            Traceback (most recent call last)
[<ipython-input-8-25d790141602>](https://localhost:8080/#) in <module>
      1 import clipit
      2 # To reset settings to default
----> 3 clipit.reset_settings()
      4 # You can use "|" to separate multiple prompts
      5 prompts = "underwater city"

AttributeError: module 'clipit' has no attribute 'reset_settings'

Getting the same issue even after Can you run setup -> restart runtime -> run setup again -> Run the generate image code.

**Comment by douwe2** [comment]
There is comment is his blog about pixray. I did not understand it at first. But is basically it means that much of what is in his blog is no longer apllicable since it has all (clip, clipit, etc) been replaced by pixray.

So just **install pixray: https://github.com/pixray/pixray**
