### ISSUE TITLE
Google Colab 'MyRandomPerspective' object has no attribute 'resample'

### ISSUE THREAD

**Issue by oonacitarhan** [mfrashad/text2art#8]
Hi there,

When I try to run your Google Colab notebook, I got an error that says: 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-08ef0e1ed468> in <module>()
     13 settings = clipit.apply_settings()
     14 clipit.do_init(settings)
---> 15 clipit.do_run(settings)

11 frames
/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in __getattr__(self, name)
   1129                 return modules[name]
   1130         raise AttributeError("'{}' object has no attribute '{}'".format(
-> 1131             type(self).__name__, name))
   1132 
   1133     def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:

AttributeError: 'MyRandomPerspective' object has no attribute 'resample'

Could you please help? Thanks!

**Comment by youssef12347** [comment]
Same issue here.

**Comment by hcorion** [comment]
Go to line 226 in clipit/clipit.py
and change it from
```python3
             mode=self.resample.name.lower(), align_corners=self.align_corners, padding_mode=global_padding_mode
```
to
```python3
             mode=self.flags["resample"].name.lower(), align_corners=self.flags["align_corners"], padding_mode=global_padding_mode
```

Alternatively you can change the install script in text2art.ipynb to install a specific version of kornia
`!python3.8 -m pip install --user kornia==0.6.1`

**Comment by hcorion** [comment]
Keep this open please, the issue is still a problem.
